"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { getCourse } from "../lib/constants.js";

export default function AppShell({ session, ai, children }) {
  const pathname = usePathname();
  const router = useRouter();
  const isHr = session?.role === "hr_admin";

  const employeeLinks = [
    { href: "/", label: "Home" },
    { href: "/assessment", label: "Self-Assessment" },
    { href: "/my-path", label: "My Learning Path" },
  ];
  const hrLinks = [
    { href: "/hr/dashboard", label: "Dashboard" },
    { href: "/hr/employees", label: "Employees" },
    { href: "/hr/training", label: "Training Library" },
    { href: "/hr/export", label: "Export" },
  ];
  const links = isHr ? hrLinks : employeeLinks;

  async function logout() {
    await fetch("/api/auth/logout", { method: "POST" });
    router.push("/login");
    router.refresh();
  }

  return (
    <>
      <header className="app-header">
        <div className="brand">
          SkillPath L&amp;D <span>Next.js MVP</span>
        </div>
        <div style={{ display: "flex", gap: "0.75rem", alignItems: "center", flexWrap: "wrap" }}>
          <span className="badge-demo">DEMO</span>
          <span className="header-meta">
            {session?.name} | {isHr ? "HR Admin" : "Employee"}
          </span>
          {ai && (
            <span className="header-meta" title="AI configuration">
              AI: {ai.configured ? ai.provider : "not configured (fallback)"}
            </span>
          )}
          <button type="button" className="btn btn-sm" onClick={logout}>
            Logout
          </button>
        </div>
      </header>
      <nav className="app-nav">
        {links.map((l) => (
          <Link key={l.href} href={l.href} className={pathname === l.href ? "active" : ""}>
            {l.label}
          </Link>
        ))}
      </nav>
      <main className="app-main">{children}</main>
    </>
  );
}

export function StatusBadge({ status }) {
  const map = {
    "Not started": "notstarted",
    Draft: "draft",
    Submitted: "submitted",
    "Not generated": "notstarted",
    "Pending HR Review": "pending",
    Approved: "approved",
    Rejected: "rejected",
    "In progress": "progress",
    Completed: "approved",
  };
  const cls = `status status-${map[status] || "notstarted"}`;
  return <span className={cls}>{status || "-"}</span>;
}

export function PlanSummary({ plan, showProgress, onProgressChange }) {
  if (!plan) return <p className="intro">No learning path yet.</p>;

  return (
    <>
      <h3>Skill Gaps</h3>
      {(plan.gaps || []).length === 0 ? (
        <p>No significant gaps identified.</p>
      ) : (
        plan.gaps.map((g) => (
          <div className="gap-item" key={g.competency_id}>
            <div>
              <strong>{g.competency_name}</strong> - rated {g.current_level}, role needs{" "}
              {g.required_level} (gap: {g.gap})
            </div>
          </div>
        ))
      )}
      <h3>Development Goals ({plan.timeline_days || 90}-day plan)</h3>
      {(plan.goals || []).map((g, i) => (
        <div className="goal-item" key={i}>
          - {g}
        </div>
      ))}
      <h3>Recommended Training</h3>
      {(plan.recommended_courses || []).map((rc) => {
        const c = getCourse(rc.course_id);
        return (
          <div className="course-item" key={rc.course_id}>
            <strong>{c?.title || rc.course_id}</strong>
            <div style={{ fontSize: "0.8rem", color: "var(--muted)", margin: "0.25rem 0" }}>
              {c
                ? `${c.format} | ${c.duration_hours}h | ${c.next_session_date}`
                : rc.course_id}
            </div>
            {showProgress ? (
              <select
                value={rc.progress}
                onChange={(e) => onProgressChange?.(rc.course_id, e.target.value)}
                style={{ marginTop: "0.5rem" }}
              >
                {["Not started", "In progress", "Completed"].map((s) => (
                  <option key={s}>{s}</option>
                ))}
              </select>
            ) : (
              <div style={{ marginTop: "0.35rem" }}>
                <StatusBadge status={rc.progress} />
              </div>
            )}
          </div>
        );
      })}
      {plan.rationale && (
        <p className="intro" style={{ marginTop: "0.75rem" }}>
          <em>{plan.rationale}</em>
        </p>
      )}
      {plan.ai_provider && (
        <p className="intro" style={{ fontSize: "0.8rem" }}>
          Generated by: {plan.ai_provider}
          {plan.ai_model ? ` / ${plan.ai_model}` : ""}
        </p>
      )}
    </>
  );
}
